//! A-144 — five hard-coded mocks of the *same* loop, so A-137's layout gets chosen by looking at it.
//!
//! **This is a comparison artifact, not a feature.** Nothing here reads a `UiEvent`, subscribes to
//! an engine, or is reachable from the live TUI: [`crate::render`] never mentions this module, and
//! `crates/flux-tui/tests/loop_mocks.rs` asserts that it stays that way. The only entry points are
//! the `loop_mocks` example and that test.
//!
//! Five renderers consume one hand-authored [`fixture`] — the tracking-plugin flow the board is
//! regenerated by — so a side-by-side comparison means something. Each renderer takes a genuinely
//! different position on what the primary object *is*:
//!
//! | mock | primary object | file |
//! |---|---|---|
//! | [`Mock::Thread`] | the sequence of steps | [`thread`] |
//! | [`Mock::Tree`] | the call structure | [`tree`] |
//! | [`Mock::Split`] | the *selected* step | [`split`] |
//! | [`Mock::Timeline`] | elapsed time | [`timeline`] |
//! | [`Mock::Graph`] | the authored program | [`graph`] |
//!
//! ## Two rules every mock obeys
//!
//! **Honesty.** A render that withholds anything records an [`Elision`] whose `marker` text is on
//! screen. The step accounting is derived in one place — `Tally::finish` computes `total - drawn`
//! rather than believing a renderer's own count — so a mock cannot under-report what it hid; it
//! can only be wrong about what it drew.
//!
//! **Bounds.** Every line leaves through [`clip`], so no mock can overflow its terminal; and each
//! declares the width below which it stops working ([`MockSpec::min_cols`]). Under that floor it
//! says so instead of drawing a mangled version of itself, which is the interesting behaviour to
//! compare — every layout has a floor, and what it does there is a design decision.
//!
//! ⚠ The fixture is hand-written data, not a captured run. That is the point (it costs a fraction
//! of A-137), and it is also the thing to be honest about: these are drawings of plausible load,
//! not measurements of real load.

use ratatui::style::{Modifier, Style};
use ratatui::text::{Line, Span};
use unicode_width::UnicodeWidthStr;

use crate::theme::Theme;

pub mod fixture;
mod graph;
mod split;
mod thread;
mod timeline;
mod tree;

pub use fixture::{fixture, Fixture, Flat, LoadCase, Status, Step, StepKind, Usage, LOAD_CASES};
pub use graph::{graph_gutter_len, graph_plan_line_count};

/// The `what` of an [`Elision`] that withheld whole steps — the one the accounting test checks.
pub const STEPS: &str = "steps";
/// The `what` of an [`Elision`] that withheld lines *within* a step's detail.
pub const DETAIL: &str = "detail lines";

/// The marker every mock puts on the step a pause would attach to (A-140). Mocked as a glyph
/// only — no key is bound and nothing pauses.
pub const PAUSE_GLYPH: &str = "⏸";

/// The five mocks, in the order the snapshot set and the example present them.
pub const MOCKS: [Mock; 5] = [
    Mock::Thread,
    Mock::Tree,
    Mock::Split,
    Mock::Timeline,
    Mock::Graph,
];

/// One of the five layout strategies.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Mock {
    /// One line per step, no indentation; structure lives in a `phase/op` scope column.
    Thread,
    /// An indented tree with the same connectors `plan.rs` draws.
    Tree,
    /// A condensed thread beside a detail pane for the step in focus.
    Split,
    /// A time axis: bar length is duration, overlap is concurrency.
    Timeline,
    /// The authored Flux-Lang DAG as the primary object, steps annotating its nodes.
    Graph,
}

/// What a mock makes *primary*. Two mocks sharing an axis would be two variations of one idea, so
/// the five are required to declare five different ones.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Axis {
    Sequence,
    Structure,
    Selection,
    Time,
    Program,
}

/// A mock's stated position: what it optimizes for, what it gives up, and where the two controls
/// this epic already owes ([A-140](../../../../docs/stories/A-140-pause-a-live-run.md)'s pause,
/// [A-142](../../../../docs/stories/A-142-inspect-a-paused-run.md)'s inspection pane) would go.
/// A layout with nowhere for either is disqualified, so both fields are required to be non-empty.
#[derive(Debug, Clone, Copy)]
pub struct MockSpec {
    pub name: &'static str,
    pub axis: Axis,
    pub optimizes_for: &'static str,
    pub gives_up: &'static str,
    /// Where A-140's pause control attaches.
    pub pause_affordance: &'static str,
    /// Where A-142's inspection pane lives.
    pub inspection_pane: &'static str,
    /// The narrowest terminal this layout still works in. Below it the mock refuses rather than
    /// mangles.
    pub min_cols: usize,
}

impl Mock {
    /// This mock's stated trade-off. See [`MockSpec`].
    pub fn spec(self) -> MockSpec {
        match self {
            Mock::Thread => thread::SPEC,
            Mock::Tree => tree::SPEC,
            Mock::Split => split::SPEC,
            Mock::Timeline => timeline::SPEC,
            Mock::Graph => graph::SPEC,
        }
    }
}

/// A terminal to draw into. Both bounds are hard: a render is asserted to fit.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Viewport {
    pub cols: usize,
    pub rows: usize,
}

/// A comfortable terminal — where every layout is at its best and none of them is under pressure.
pub const WIDE: Viewport = Viewport {
    cols: 100,
    rows: 28,
};
/// A split editor pane: the width most of this is actually read at.
pub const NARROW: Viewport = Viewport { cols: 52, rows: 20 };
/// A phone-sized sliver — at or below several mocks' floor, on purpose.
pub const FLOOR: Viewport = Viewport { cols: 30, rows: 14 };

/// Something a render withheld, and the on-screen text that admits it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Elision {
    /// [`STEPS`] or [`DETAIL`].
    pub what: &'static str,
    pub hidden: usize,
    /// A substring that must appear in the drawn output. This is the honesty check.
    pub marker: String,
}

/// One mock's drawing of one fixture at one viewport.
#[derive(Debug, Clone)]
pub struct Render {
    pub lines: Vec<Line<'static>>,
    /// Everything withheld, each naming the text on screen that says so.
    pub elisions: Vec<Elision>,
    /// How many of the fixture's steps this drawing actually represents.
    pub steps_drawn: usize,
    /// The viewport is narrower than [`MockSpec::min_cols`]; what was drawn is a refusal notice,
    /// not the layout.
    pub below_floor: bool,
}

impl Render {
    /// The drawing as plain text — what the snapshot set commits and what the tests read.
    pub fn to_plain(&self) -> String {
        let mut out = String::new();
        for line in &self.lines {
            for span in &line.spans {
                out.push_str(&span.content);
            }
            out.push('\n');
        }
        out
    }

    /// `(index, width)` of every line wider than `cols`. Empty is the invariant.
    pub fn overflowing(&self, cols: usize) -> Vec<(usize, usize)> {
        self.lines
            .iter()
            .enumerate()
            .filter_map(|(i, l)| {
                let w: usize = l.spans.iter().map(|s| width(&s.content)).sum();
                (w > cols).then_some((i, w))
            })
            .collect()
    }
}

/// Draw `mock` on the `case` fixture at `vp`.
pub fn render(mock: Mock, case: LoadCase, vp: Viewport, theme: &Theme) -> Render {
    let spec = mock.spec();
    let fx = fixture(case);
    if vp.cols < spec.min_cols || vp.rows < MIN_ROWS {
        return below_floor(&spec, vp, theme);
    }
    let mut tally = Tally::new(fx.step_count());
    let body = match mock {
        Mock::Thread => thread::draw(&fx, vp, theme, &mut tally),
        Mock::Tree => tree::draw(&fx, vp, theme, &mut tally),
        Mock::Split => split::draw(&fx, vp, theme, &mut tally),
        Mock::Timeline => timeline::draw(&fx, vp, theme, &mut tally),
        Mock::Graph => graph::draw(&fx, vp, theme, &mut tally),
    };
    tally.finish(body, vp, theme)
}

/// Fewer rows than this and no layout has anything to say.
const MIN_ROWS: usize = 6;

/// What a mock draws under its own floor: a refusal that names the width it needs. Silently
/// degrading here would teach exactly the wrong lesson — every layout has a floor, and the
/// question A-137 has to answer is what happens at it, not whether one exists.
fn below_floor(spec: &MockSpec, vp: Viewport, theme: &Theme) -> Render {
    let lines = vec![
        clip(
            Line::from(Span::styled(
                spec.name.to_string(),
                Style::default().add_modifier(Modifier::BOLD),
            )),
            vp.cols,
        ),
        clip(
            Line::from(Span::styled(
                format!("needs {} cols", spec.min_cols),
                theme.warn_style(),
            )),
            vp.cols,
        ),
        clip(
            Line::from(Span::styled(
                format!("have {}", vp.cols),
                theme.muted_style(),
            )),
            vp.cols,
        ),
    ];
    Render {
        lines,
        elisions: Vec::new(),
        steps_drawn: 0,
        below_floor: true,
    }
}

/// The central step accounting. A renderer reports what it drew; the hidden count is derived here
/// as `total - drawn` so it cannot drift from reality, and the footer that admits it is appended
/// last, into a row reserved for exactly that purpose.
pub(crate) struct Tally {
    total: usize,
    drawn: usize,
    extra: Vec<Elision>,
}

impl Tally {
    fn new(total: usize) -> Self {
        Self {
            total,
            drawn: 0,
            extra: Vec::new(),
        }
    }

    /// Record that `n` of the fixture's steps are represented in the drawing.
    pub(crate) fn drew(&mut self, n: usize) {
        self.drawn += n;
    }

    /// Record a non-step elision (a truncated detail body). `marker` must be on screen.
    pub(crate) fn hid(&mut self, what: &'static str, hidden: usize, marker: String) {
        if hidden > 0 {
            self.extra.push(Elision {
                what,
                hidden,
                marker,
            });
        }
    }

    /// The row every renderer must leave free for the elision footer.
    pub(crate) fn footer_rows(&self) -> usize {
        1
    }

    fn finish(self, mut lines: Vec<Line<'static>>, vp: Viewport, theme: &Theme) -> Render {
        let mut elisions = self.extra;
        let hidden = self.total.saturating_sub(self.drawn);
        if hidden > 0 {
            // The footer is the last thing dropped, never the first: a render that ran out of rows
            // for its own admission of elision would be the exact failure this module is about.
            lines.truncate(vp.rows.saturating_sub(1));
            let marker = elision_marker(hidden, self.total);
            lines.push(clip(
                Line::from(Span::styled(marker.clone(), theme.warn_style())),
                vp.cols,
            ));
            elisions.push(Elision {
                what: STEPS,
                hidden,
                marker,
            });
        }
        lines.truncate(vp.rows);
        Render {
            lines,
            elisions,
            steps_drawn: self.drawn,
            below_floor: false,
        }
    }
}

/// The one sentence a mock says when it is not showing everything. Deliberately identical across
/// the five: the comparison is about layout, and a mock that phrased its own dishonesty more
/// prettily would win for the wrong reason.
fn elision_marker(hidden: usize, total: usize) -> String {
    format!("… {hidden} of {total} steps not shown")
}

/// Display width of `s`, the one definition the whole module shares.
pub(crate) fn width(s: &str) -> usize {
    UnicodeWidthStr::width(s)
}

/// Truncate a styled line to `cols`, marking the cut with `…`. Every line a mock emits goes
/// through here — that is what makes "no mock overflows its terminal" a property rather than a
/// hope. The `…` is itself the visible-elision rule applied per line.
pub(crate) fn clip(line: Line<'static>, cols: usize) -> Line<'static> {
    let total: usize = line.spans.iter().map(|s| width(&s.content)).sum();
    if total <= cols {
        return line;
    }
    if cols == 0 {
        return Line::default();
    }
    let budget = cols - 1;
    let mut used = 0usize;
    let mut out: Vec<Span<'static>> = Vec::new();
    for span in line.spans {
        let w = width(&span.content);
        if used + w <= budget {
            used += w;
            out.push(span);
            continue;
        }
        let mut kept = String::new();
        for ch in span.content.chars() {
            let cw = width(ch.encode_utf8(&mut [0u8; 4]));
            if used + cw > budget {
                break;
            }
            used += cw;
            kept.push(ch);
        }
        if !kept.is_empty() {
            out.push(Span::styled(kept, span.style));
        }
        break;
    }
    out.push(Span::raw("…"));
    Line::from(out)
}

/// Truncate a plain string to `cols`, marking the cut. The string twin of [`clip`], for the rows
/// a renderer assembles as text before styling them.
pub(crate) fn shorten(s: &str, cols: usize) -> String {
    if width(s) <= cols {
        return s.to_string();
    }
    let mut out = String::new();
    let mut used = 0;
    for ch in s.chars() {
        let w = width(ch.encode_utf8(&mut [0u8; 4]));
        if used + w + 1 > cols {
            break;
        }
        used += w;
        out.push(ch);
    }
    out.push('…');
    out
}

/// [`shorten`], then padded back out to exactly `cols` — for a column whose right edge has to stay
/// put whatever the content does.
pub(crate) fn fit(s: &str, cols: usize) -> String {
    let out = shorten(s, cols);
    let used = width(&out);
    format!("{out}{}", " ".repeat(cols.saturating_sub(used)))
}

/// Pad a line out to exactly `cols` — the split mock's left column, so the divider stays vertical.
pub(crate) fn pad(line: Line<'static>, cols: usize) -> Line<'static> {
    let mut line = clip(line, cols);
    let used: usize = line.spans.iter().map(|s| width(&s.content)).sum();
    if used < cols {
        line.spans.push(Span::raw(" ".repeat(cols - used)));
    }
    line
}

/// A `budget`-row window over `items` that keeps `focus` on screen, preferring context before it.
///
/// This is what a live view does once the run outgrows the terminal, and putting it here rather
/// than in each renderer keeps the comparison fair: three of the five scroll, and if they scrolled
/// differently the winner would be decided by scroll policy instead of by layout. A caller that
/// scrolled (`start > 0`) spends its first visible row saying so.
pub(crate) fn window<T>(items: &[T], budget: usize, focus: usize) -> (usize, &[T]) {
    if items.len() <= budget {
        return (0, items);
    }
    let before = budget.saturating_sub(1) / 2;
    let start = focus.saturating_sub(before).min(items.len() - budget);
    (start, &items[start..start + budget])
}

/// `1.4s` / `480ms` — the elapsed convention the TUI already uses for tool cards.
pub(crate) fn ms(v: u64) -> String {
    if v >= 1000 {
        format!("{:.1}s", v as f64 / 1000.0)
    } else {
        format!("{v}ms")
    }
}

/// `8.4k` — token counts, short enough to sit in a status column.
pub(crate) fn tokens(v: u64) -> String {
    if v >= 1000 {
        format!("{:.1}k", v as f64 / 1000.0)
    } else {
        v.to_string()
    }
}

/// The run header every mock draws, so the comparison is of the layout and not of its chrome.
pub(crate) fn header(fx: &Fixture, vp: Viewport, theme: &Theme, sub: &str) -> Line<'static> {
    let left = format!("◆ {}  {sub}", fx.title);
    let right = format!("{} elapsed", ms(fx.elapsed_ms));
    let gap = vp.cols.saturating_sub(width(&left) + width(&right)).max(1);
    clip(
        Line::from(vec![
            Span::styled("◆ ", theme.accent_style()),
            Span::styled(
                fx.title.clone(),
                Style::default().add_modifier(Modifier::BOLD),
            ),
            Span::styled(format!("  {sub}"), theme.muted_style()),
            Span::raw(" ".repeat(gap)),
            Span::styled(right, theme.muted_style()),
        ]),
        vp.cols,
    )
}

/// Colour for a step's status glyph, shared so the five read as one product.
pub(crate) fn status_style(status: Status, theme: &Theme) -> Style {
    match status {
        Status::Done => theme.ok_style(),
        Status::Running => theme.accent_style(),
        Status::Failed => theme.err_style(),
        Status::Pending => theme.muted_style(),
    }
}

/// The recommendation this story exists to produce. Five pictures and no decision is the failure
/// mode, so the decision ships in the artifact rather than only in a review comment.
pub const RECOMMENDATION: &str = "\
BUILD MOCK 3 — the split (condensed rail + detail pane) — with mock 1 as its narrow fallback.

Why, from the snapshots and not from taste. The question a live view has to keep answering while
the run moves is \"what is it doing right now, and is that reasonable\". Read the 49-step long-run
row of the matrix: the thread and the tree both scroll 23 rows away from the start and can show
only a window; the timeline shows bars with no content; the graph shows a program that does not
contain the running phase at all. The split is the only one that still shows the *whole* run —
all nine phases, because a finished phase stays one row — and the current command, and its
timing, at the same time. On the deep-nesting case it is the only layout that shows the model
call's token cost and its streaming tail next to the chain that produced it. Both of those come
from the same property: the rail's height is set by the program's phase count while the pane's
content is set by one step, so neither grows with the run.

The two controls this epic already owes settle it. A-140's pause has an unambiguous home (the
focused rail row) and A-142's inspection pane does not need building — the right column already
is it. The other four all have to answer \"where does the pane go\" with a sheet or a bottom
split, which means A-142 would relayout whatever A-137 shipped.

What it gives up — the honest list.
  1. Width, badly. 64 columns, the highest floor of the five, and the snapshots show it refusing
     in *every* case at 52 columns while all four others still draw. This is the one place the
     split is the worst option, and it is not a small place. Hence the fallback: below 64 columns
     A-137 should render mock 1 (the flat thread) rather than refuse — the mocks refuse instead,
     deliberately, so the cost shows up in the picture rather than in a footnote.
  2. Content in the rail. At 40 rail columns a leaf row is down to `→ read  7.4s` — the rail
     carries structure and status, and the *what* lives only in the pane. Compare the fan-out
     case: the tree shows six workers and what each is doing; the split shows six workers and
     what one is doing.
  3. One narrative. A rail beside a pane is not something you scroll back through. This answers
     the design doc's open question (\"scrollback-inline or a pane\") in favour of the pane, and
     the transcript keeps the scrollback.
  4. Focus state. It is the only layout needing a selection, so it is the only one needing input
     handling and a focus policy — follow the running step, or hold where the operator put it —
     before it renders correctly at all. Budget that into A-137; the other four do not spend it.

Runner-up: mock 2, the tree. At 100 columns it is the most legible drawing of what a run is
*shaped* like and the only one where a fan-out looks like a fan-out. It loses on the width tax:
indentation compounds, and by the deep-nesting case at 52 columns the connectors have taken half
the terminal. Take its connectors with you — the split's pane already draws its children with
them, and that is not a coincidence.

Do not build as the top-level view: mock 1 alone (the scope column gets squeezed exactly when
there is enough structure for it to matter, and concurrency reads as interleaving), or mock 5.
Mock 5 is the right answer for A-138's expansion and the wrong one for a live view — its
snapshots show why twice over: the program does not move, so most rows are always the parts that
are not running, and mapping runtime steps back onto program nodes misattributes as soon as a
sub-agent runs a program of its own (see the fan-out case, where six workers' `glob` calls land
on the parent's `glob` node). A-138 should expand *one step* into its graph, which is exactly
what the split's pane has room to do.";

/// The committed side-by-side comparison, as markdown. This is the artifact a reviewer reads
/// instead of running anything; `the_snapshot_set_matches_the_renderers` keeps it honest.
pub fn snapshot_document() -> String {
    let theme = Theme::MONO;
    let mut out = String::new();
    out.push_str(
        "<!-- GENERATED by `cargo test -p flux-tui --test loop_mocks` (A-144). Do not hand-edit;\n\
         regenerate with FLUX_UPDATE_GOLDEN=1, which rewrites this file and then fails on purpose. -->\n\n",
    );
    out.push_str("# A-144 — five loop-view mocks, side by side\n\n");
    out.push_str(
        "Five hard-coded layouts drawing one hand-authored fixture (the tracking-plugin flow:\n\
         validate frontmatter → regenerate the board → audit epics for missing trackers → sync the\n\
         CHANGELOG, with a model-authored judgement step in the middle). Nothing here is wired to a\n\
         live run; see `crates/flux-tui/src/loopmock/mod.rs`.\n\n\
         Each mock is drawn under the tidy case **and** the three that decide the question — a long\n\
         run, deep nesting, a sub-agent fan-out — plus a narrow terminal and one below its floor.\n\n",
    );

    out.push_str("## The recommendation\n\n```text\n");
    out.push_str(RECOMMENDATION);
    out.push_str("\n```\n\n## At a glance\n\n");
    out.push_str("| mock | primary axis | optimizes for | gives up | min cols |\n");
    out.push_str("|---|---|---|---|---|\n");
    for mock in MOCKS {
        let s = mock.spec();
        out.push_str(&format!(
            "| {} | {:?} | {} | {} | {} |\n",
            s.name, s.axis, s.optimizes_for, s.gives_up, s.min_cols
        ));
    }
    out.push('\n');

    for mock in MOCKS {
        let s = mock.spec();
        out.push_str(&format!("## {}\n\n", s.name));
        out.push_str(&format!("- **Primary axis:** {:?}\n", s.axis));
        out.push_str(&format!("- **Optimizes for:** {}\n", s.optimizes_for));
        out.push_str(&format!("- **Gives up:** {}\n", s.gives_up));
        out.push_str(&format!(
            "- **A-140 pause control:** {}\n",
            s.pause_affordance
        ));
        out.push_str(&format!(
            "- **A-142 inspection pane:** {}\n",
            s.inspection_pane
        ));
        out.push_str(&format!(
            "- **Floor:** {} cols (below it, it says so)\n\n",
            s.min_cols
        ));

        for case in LOAD_CASES {
            for vp in [WIDE, NARROW] {
                let r = render(mock, case, vp, &theme);
                out.push_str(&format!(
                    "### {} · {} · {}×{}\n\n",
                    s.name,
                    case.name(),
                    vp.cols,
                    vp.rows
                ));
                if !r.elisions.is_empty() {
                    let notes: Vec<String> = r
                        .elisions
                        .iter()
                        .map(|e| format!("{} {}", e.hidden, e.what))
                        .collect();
                    out.push_str(&format!("_withheld: {}_\n\n", notes.join(", ")));
                }
                out.push_str("```text\n");
                out.push_str(&r.to_plain());
                out.push_str("```\n\n");
            }
        }

        let under = Viewport {
            cols: s.min_cols - 1,
            rows: 14,
        };
        let r = render(mock, LoadCase::Tidy, under, &theme);
        out.push_str(&format!(
            "### {} · below its floor · {}×{}\n\n```text\n{}```\n\n",
            s.name,
            under.cols,
            under.rows,
            r.to_plain()
        ));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn clip_never_exceeds_its_budget_and_marks_the_cut() {
        let line = Line::from(vec![Span::raw("abcdef"), Span::raw("ghijkl")]);
        let out = clip(line, 8);
        let text: String = out.spans.iter().map(|s| s.content.to_string()).collect();
        assert_eq!(text, "abcdefg…");
        assert_eq!(width(&text), 8);
    }

    #[test]
    fn clip_leaves_a_fitting_line_alone() {
        let line = Line::from(Span::raw("short"));
        assert_eq!(clip(line, 40).spans[0].content, "short");
    }

    #[test]
    fn pad_squares_a_column_off() {
        let out = pad(Line::from(Span::raw("ab")), 6);
        let text: String = out.spans.iter().map(|s| s.content.to_string()).collect();
        assert_eq!(width(&text), 6);
    }

    #[test]
    fn the_tally_derives_the_hidden_count_rather_than_trusting_a_renderer() {
        let mut tally = Tally::new(20);
        tally.drew(7);
        let render = tally.finish(Vec::new(), WIDE, &Theme::MONO);
        assert_eq!(render.elisions.len(), 1);
        assert_eq!(render.elisions[0].hidden, 13);
        assert!(render.to_plain().contains(&render.elisions[0].marker));
    }

    #[test]
    fn a_complete_drawing_admits_nothing() {
        let mut tally = Tally::new(4);
        tally.drew(4);
        assert!(tally
            .finish(Vec::new(), WIDE, &Theme::MONO)
            .elisions
            .is_empty());
    }
}
