//! A-144 — five hard-coded mocks of the *same* loop, so A-137's layout gets chosen by looking at it.
//!
//! **This is a comparison artifact, not a feature.** Nothing here reads a `UiEvent`, subscribes to
//! an engine, or is reachable from the live TUI: [`crate::render`] never mentions this module, and
//! `crates/flux-tui/tests/loop_mocks.rs` asserts that it stays that way. The only entry points are
//! the `loop_mocks` example and that test.
//!
//! Five renderers consume one hand-authored [`fixture`] — the tracking-plugin flow the board is
//! regenerated by — so a side-by-side comparison means something. Each renderer takes a genuinely
//! different position on what the primary object *is*:
//!
//! | mock | primary object | file |
//! |---|---|---|
//! | [`Mock::Thread`] | the sequence of steps | [`thread`] |
//! | [`Mock::Tree`] | the call structure | [`tree`] |
//! | [`Mock::Split`] | the *selected* step | [`split`] |
//! | [`Mock::Timeline`] | elapsed time | [`timeline`] |
//! | [`Mock::Graph`] | the authored program | [`graph`] |
//!
//! ## Two rules every mock obeys
//!
//! **Honesty.** A render that withholds anything records an [`Elision`] whose `marker` text is on
//! screen. Both halves are enforced centrally rather than trusted to each renderer: `Tally::finish`
//! derives the hidden step count as `total - drawn`, so a mock cannot under-report what it hid, and
//! it *forces* any recorded marker that did not survive composition back onto the screen. The
//! second half exists because it was once false — at `rows == 6` mock 3's pane assembled more lines
//! than the compose loop kept, so its `+N more` was cut while the elision stayed on the books. A
//! silent truncation with a comforting entry in a struct nobody sees is the exact failure this
//! module is about, so the property is now unconditional over every viewport [`render`] accepts,
//! and `crates/flux-tui/tests/loop_mocks.rs` sweeps that envelope rather than sampling the three
//! sizes the snapshot set happens to present.
//!
//! **Bounds.** Every line leaves through [`clip`], so no mock can overflow its terminal; and each
//! declares *two* floors, [`MockSpec::min_cols`] and [`MockSpec::min_rows`]. Under either it says
//! so instead of drawing a mangled version of itself, which is the interesting behaviour to
//! compare — every layout has a floor, what it does there is a design decision, and a layout's cost
//! is two numbers rather than one.
//!
//! ⚠ **Provenance (A-145).** Two of the four load cases are now reconstructed from a real recorded
//! session ([`capture`]); two are still hand-authored, because the durable log cannot currently
//! produce them. Which is which is drawn in every header, never left to a doc comment — a
//! comparison that silently mixes measured and invented load is worse than either kind alone.

use ratatui::style::{Modifier, Style};
use ratatui::text::{Line, Span};
use unicode_width::UnicodeWidthStr;

use crate::theme::Theme;

pub mod axes;
pub mod capture;
pub mod fixture;
mod graph;
mod split;
mod thread;
mod timeline;
mod tree;

pub use axes::{render_axes, Axes, Depth, Shape, AXIS_SPACE};
pub use capture::{Fidelity, FidelityRow, FIDELITY};
pub use fixture::{
    fixture, Fixture, Flat, LoadCase, Provenance, Status, Step, StepKind, Usage, LOAD_CASES,
};
pub use graph::{graph_gutter_len, graph_plan_line_count};

/// The `what` of an [`Elision`] that withheld whole steps — the one the accounting test checks.
pub const STEPS: &str = "steps";
/// The `what` of an [`Elision`] that withheld lines *within* a step's detail.
pub const DETAIL: &str = "detail lines";
/// The `what` of an [`Elision`] that collapsed a finished subtree into its own row ([`axes`]).
pub const CONDENSED: &str = "condensed steps";
/// The `what` of an [`Elision`] that stopped descending at a depth limit ([`axes`]). Counted in
/// **levels**, not steps: "some of it is deeper" is not an answer a reader can act on.
pub const LEVELS: &str = "nesting levels";

/// The marker every mock puts on the step a pause would attach to (A-140). Mocked as a glyph
/// only — no key is bound and nothing pauses.
pub const PAUSE_GLYPH: &str = "⏸";

/// The five mocks, in the order the snapshot set and the example present them.
pub const MOCKS: [Mock; 5] = [
    Mock::Thread,
    Mock::Tree,
    Mock::Split,
    Mock::Timeline,
    Mock::Graph,
];

/// One of the five layout strategies.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Mock {
    /// One line per step, no indentation; structure lives in a `phase/op` scope column.
    Thread,
    /// An indented tree with the same connectors `plan.rs` draws.
    Tree,
    /// A condensed thread beside a detail pane for the step in focus.
    Split,
    /// A time axis: bar length is duration, overlap is concurrency.
    Timeline,
    /// The authored Flux-Lang DAG as the primary object, steps annotating its nodes.
    Graph,
}

/// What a mock makes *primary*. Two mocks sharing an axis would be two variations of one idea, so
/// the five are required to declare five different ones.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Axis {
    Sequence,
    Structure,
    Selection,
    Time,
    Program,
}

/// A mock's stated position: what it optimizes for, what it gives up, and where the two controls
/// this epic already owes ([A-140](../../../../docs/stories/A-140-pause-a-live-run.md)'s pause,
/// [A-142](../../../../docs/stories/A-142-inspect-a-paused-run.md)'s inspection pane) would go.
/// A layout with nowhere for either is disqualified, so both fields are required to be non-empty.
#[derive(Debug, Clone, Copy)]
pub struct MockSpec {
    pub name: &'static str,
    pub axis: Axis,
    pub optimizes_for: &'static str,
    pub gives_up: &'static str,
    /// Where A-140's pause control attaches.
    pub pause_affordance: &'static str,
    /// Where A-142's inspection pane lives.
    pub inspection_pane: &'static str,
    /// The narrowest terminal this layout still works in. Below it the mock refuses rather than
    /// mangles.
    pub min_cols: usize,
    /// The shortest terminal this layout still works in — its floor in the *other* dimension.
    ///
    /// Rows have a floor for the same reason columns do, and one mock's is much higher than the
    /// rest: mock 3's pane spends four rows on chrome (breadcrumb, header, timing, rule) before it
    /// says anything, and it must still have room for a body row, an elision marker and the hint.
    /// Discovering that is part of what the comparison is for — a layout's cost is two numbers,
    /// not one.
    pub min_rows: usize,
}

impl Mock {
    /// This mock's stated trade-off. See [`MockSpec`].
    pub fn spec(self) -> MockSpec {
        match self {
            Mock::Thread => thread::SPEC,
            Mock::Tree => tree::SPEC,
            Mock::Split => split::SPEC,
            Mock::Timeline => timeline::SPEC,
            Mock::Graph => graph::SPEC,
        }
    }
}

/// A terminal to draw into. Both bounds are hard: a render is asserted to fit.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Viewport {
    pub cols: usize,
    pub rows: usize,
}

/// A comfortable terminal — where every layout is at its best and none of them is under pressure.
pub const WIDE: Viewport = Viewport {
    cols: 100,
    rows: 28,
};
/// A split editor pane: the width most of this is actually read at.
pub const NARROW: Viewport = Viewport { cols: 52, rows: 20 };
/// A phone-sized sliver — at or below several mocks' floor, on purpose.
pub const FLOOR: Viewport = Viewport { cols: 30, rows: 14 };

/// Something a render withheld, and the on-screen text that admits it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Elision {
    /// [`STEPS`] or [`DETAIL`].
    pub what: &'static str,
    pub hidden: usize,
    /// A substring that must appear in the drawn output. This is the honesty check.
    pub marker: String,
}

/// One mock's drawing of one fixture at one viewport.
#[derive(Debug, Clone)]
pub struct Render {
    pub lines: Vec<Line<'static>>,
    /// Everything withheld, each naming the text on screen that says so.
    pub elisions: Vec<Elision>,
    /// **Which** of the fixture's steps this drawing represents, by [`Step::id`].
    ///
    /// ⚠ Identities rather than a count, and A-145 is why: on the long-run case the split and the
    /// flat thread both report `166 of 191 steps not shown`, and they are not hiding the same 166.
    /// A comparison done on counts would have called those two layouts equivalent. Everything in
    /// [`axes`] that compares one view with another compares this set.
    pub represented: std::collections::BTreeSet<usize>,
    /// The viewport is under [`MockSpec::min_cols`] or [`MockSpec::min_rows`]; what was drawn is a
    /// refusal notice naming the dimension, not the layout.
    pub below_floor: bool,
}

impl Render {
    /// How many of the fixture's steps this drawing represents.
    pub fn steps_drawn(&self) -> usize {
        self.represented.len()
    }

    /// The drawing as plain text — what the snapshot set commits and what the tests read.
    pub fn to_plain(&self) -> String {
        let mut out = String::new();
        for line in &self.lines {
            for span in &line.spans {
                out.push_str(&span.content);
            }
            out.push('\n');
        }
        out
    }

    /// `(index, width)` of every line wider than `cols`. Empty is the invariant.
    pub fn overflowing(&self, cols: usize) -> Vec<(usize, usize)> {
        self.lines
            .iter()
            .enumerate()
            .filter_map(|(i, l)| {
                let w: usize = l.spans.iter().map(|s| width(&s.content)).sum();
                (w > cols).then_some((i, w))
            })
            .collect()
    }
}

/// Draw `mock` on the `case` fixture at `vp`.
pub fn render(mock: Mock, case: LoadCase, vp: Viewport, theme: &Theme) -> Render {
    let spec = mock.spec();
    let fx = fixture(case);
    if vp.cols < spec.min_cols || vp.rows < spec.min_rows {
        return below_floor(spec.name, spec.min_cols, spec.min_rows, vp, theme);
    }
    let mut tally = Tally::new(fx.step_count());
    let body = match mock {
        Mock::Thread => thread::draw(&fx, vp, theme, &mut tally),
        Mock::Tree => tree::draw(&fx, vp, theme, &mut tally),
        Mock::Split => split::draw(&fx, vp, theme, &mut tally),
        Mock::Timeline => timeline::draw(&fx, vp, theme, &mut tally),
        Mock::Graph => graph::draw(&fx, vp, theme, &mut tally),
    };
    tally.finish(body, vp, theme)
}

/// Fewer rows than this and no layout has anything to say, so no [`MockSpec::min_rows`] may be
/// lower. It is a sanity bound on the specs, not the envelope itself — the envelope is per mock.
pub const MIN_ROWS: usize = 6;

/// What a layout draws under its own floor: a refusal naming the dimension it is short of. Silently
/// degrading here would teach exactly the wrong lesson — every layout has a floor, and the
/// question A-137 has to answer is what happens at it, not whether one exists.
///
/// Takes the floor as two numbers rather than a [`MockSpec`] because since A-146 the floor is not
/// always a constant of a layout: the composed view's is a function of its [`Axes`], and the whole
/// point of making the detail pane optional was to find out whether its 64×10 floor travels with it.
pub(crate) fn below_floor(
    name: &str,
    min_cols: usize,
    min_rows: usize,
    vp: Viewport,
    theme: &Theme,
) -> Render {
    let (need, have) = if vp.cols < min_cols {
        (
            format!("needs {min_cols} cols"),
            format!("have {}", vp.cols),
        )
    } else {
        (
            format!("needs {min_rows} rows"),
            format!("have {}", vp.rows),
        )
    };
    let mut lines = vec![
        clip(
            Line::from(Span::styled(
                name.to_string(),
                Style::default().add_modifier(Modifier::BOLD),
            )),
            vp.cols,
        ),
        clip(Line::from(Span::styled(need, theme.warn_style())), vp.cols),
        clip(Line::from(Span::styled(have, theme.muted_style())), vp.cols),
    ];
    lines.truncate(vp.rows);
    Render {
        lines,
        elisions: Vec::new(),
        represented: std::collections::BTreeSet::new(),
        below_floor: true,
    }
}

/// The central step accounting. A renderer reports what it drew; the hidden count is derived here
/// as `total - drawn` so it cannot drift from reality, and the footer that admits it is appended
/// last, into a row reserved for exactly that purpose.
pub(crate) struct Tally {
    total: usize,
    drawn: std::collections::BTreeSet<usize>,
    extra: Vec<Elision>,
}

impl Tally {
    pub(crate) fn new(total: usize) -> Self {
        Self {
            total,
            drawn: std::collections::BTreeSet::new(),
            extra: Vec::new(),
        }
    }

    /// Record **which** of the fixture's steps are represented in the drawing.
    ///
    /// Identities rather than a count since A-146: two layouts that hide the same *number* of steps
    /// can be hiding entirely different ones, which is precisely what A-145 measured, so a count is
    /// not a thing two views can be compared on. It also makes double-counting unrepresentable.
    pub(crate) fn drew(&mut self, ids: impl IntoIterator<Item = usize>) {
        self.drawn.extend(ids);
    }

    /// Record a non-step elision (a truncated detail body). `marker` must be on screen.
    pub(crate) fn hid(&mut self, what: &'static str, hidden: usize, marker: String) {
        if hidden > 0 {
            self.extra.push(Elision {
                what,
                hidden,
                marker,
            });
        }
    }

    /// The row every renderer must leave free for the elision footer.
    pub(crate) fn footer_rows(&self) -> usize {
        1
    }

    /// Compose the final render, enforcing the module's honesty property rather than trusting the
    /// renderer to have got it right.
    ///
    /// A recorded elision whose marker did not survive to the screen is not a disclosed elision —
    /// it is a silent truncation with a comforting entry in a struct nobody sees. So the markers
    /// are made present *here*, after the viewport bound is applied, displacing the last rows if it
    /// comes to that. Every renderer is written so this never has to fire; it fires anyway if one
    /// of them is ever wrong, which is the point of putting it in the one place that owns the
    /// property. Dropping the record instead would be the tempting fix and the dishonest one.
    pub(crate) fn finish(
        self,
        mut lines: Vec<Line<'static>>,
        vp: Viewport,
        theme: &Theme,
    ) -> Render {
        let mut elisions = self.extra;
        let hidden = self.total.saturating_sub(self.drawn.len());
        // Rows the step footer will need. Reserved before anything else competes for them: a
        // render that ran out of room for its own admission of elision is the exact failure this
        // module is about.
        let reserved = usize::from(hidden > 0);
        lines.truncate(vp.rows.saturating_sub(reserved));

        let drawn_text = |lines: &[Line<'static>]| -> String {
            lines
                .iter()
                .flat_map(|l| l.spans.iter().map(|s| s.content.to_string()))
                .collect()
        };
        let text = drawn_text(&lines);
        let missing: Vec<String> = elisions
            .iter()
            .filter(|e| !text.contains(&e.marker))
            .map(|e| e.marker.clone())
            .collect();
        for (i, marker) in missing.iter().enumerate() {
            let row = lines
                .len()
                .saturating_sub(missing.len() - i)
                .min(lines.len());
            let line = clip(
                Line::from(Span::styled(marker.clone(), theme.warn_style())),
                vp.cols,
            );
            match lines.get_mut(row) {
                Some(slot) => *slot = line,
                None => lines.push(line),
            }
        }

        if hidden > 0 {
            let marker = elision_marker(hidden, self.total);
            lines.push(clip(
                Line::from(Span::styled(marker.clone(), theme.warn_style())),
                vp.cols,
            ));
            elisions.push(Elision {
                what: STEPS,
                hidden,
                marker,
            });
        }
        lines.truncate(vp.rows);
        Render {
            lines,
            elisions,
            represented: self.drawn,
            below_floor: false,
        }
    }
}

/// The one sentence a mock says when it is not showing everything. Deliberately identical across
/// the five: the comparison is about layout, and a mock that phrased its own dishonesty more
/// prettily would win for the wrong reason.
fn elision_marker(hidden: usize, total: usize) -> String {
    format!("… {hidden} of {total} steps not shown")
}

/// Display width of `s`, the one definition the whole module shares.
pub(crate) fn width(s: &str) -> usize {
    UnicodeWidthStr::width(s)
}

/// Truncate a styled line to `cols`, marking the cut with `…`. Every line a mock emits goes
/// through here — that is what makes "no mock overflows its terminal" a property rather than a
/// hope. The `…` is itself the visible-elision rule applied per line.
pub(crate) fn clip(line: Line<'static>, cols: usize) -> Line<'static> {
    let total: usize = line.spans.iter().map(|s| width(&s.content)).sum();
    if total <= cols {
        return line;
    }
    if cols == 0 {
        return Line::default();
    }
    let budget = cols - 1;
    let mut used = 0usize;
    let mut out: Vec<Span<'static>> = Vec::new();
    for span in line.spans {
        let w = width(&span.content);
        if used + w <= budget {
            used += w;
            out.push(span);
            continue;
        }
        let mut kept = String::new();
        for ch in span.content.chars() {
            let cw = width(ch.encode_utf8(&mut [0u8; 4]));
            if used + cw > budget {
                break;
            }
            used += cw;
            kept.push(ch);
        }
        if !kept.is_empty() {
            out.push(Span::styled(kept, span.style));
        }
        break;
    }
    out.push(Span::raw("…"));
    Line::from(out)
}

/// Truncate a plain string to `cols`, marking the cut. The string twin of [`clip`], for the rows
/// a renderer assembles as text before styling them.
pub(crate) fn shorten(s: &str, cols: usize) -> String {
    if width(s) <= cols {
        return s.to_string();
    }
    let mut out = String::new();
    let mut used = 0;
    for ch in s.chars() {
        let w = width(ch.encode_utf8(&mut [0u8; 4]));
        if used + w + 1 > cols {
            break;
        }
        used += w;
        out.push(ch);
    }
    out.push('…');
    out
}

/// [`shorten`], then padded back out to exactly `cols` — for a column whose right edge has to stay
/// put whatever the content does.
pub(crate) fn fit(s: &str, cols: usize) -> String {
    let out = shorten(s, cols);
    let used = width(&out);
    format!("{out}{}", " ".repeat(cols.saturating_sub(used)))
}

/// Pad a line out to exactly `cols` — the split mock's left column, so the divider stays vertical.
pub(crate) fn pad(line: Line<'static>, cols: usize) -> Line<'static> {
    let mut line = clip(line, cols);
    let used: usize = line.spans.iter().map(|s| width(&s.content)).sum();
    if used < cols {
        line.spans.push(Span::raw(" ".repeat(cols - used)));
    }
    line
}

/// A `budget`-row window over `items` that keeps `focus` on screen, preferring context before it.
///
/// This is what a live view does once the run outgrows the terminal, and putting it here rather
/// than in each renderer keeps the comparison fair: three of the five scroll, and if they scrolled
/// differently the winner would be decided by scroll policy instead of by layout. A caller that
/// scrolled (`start > 0`) spends its first visible row saying so.
pub(crate) fn window<T>(items: &[T], budget: usize, focus: usize) -> (usize, &[T]) {
    if items.len() <= budget {
        return (0, items);
    }
    let before = budget.saturating_sub(1) / 2;
    let start = focus.saturating_sub(before).min(items.len() - budget);
    (start, &items[start..start + budget])
}

/// `1.4s` / `480ms` — the elapsed convention the TUI already uses for tool cards.
pub(crate) fn ms(v: u64) -> String {
    if v >= 1000 {
        format!("{:.1}s", v as f64 / 1000.0)
    } else {
        format!("{v}ms")
    }
}

/// `8.4k` — token counts, short enough to sit in a status column.
pub(crate) fn tokens(v: u64) -> String {
    if v >= 1000 {
        format!("{:.1}k", v as f64 / 1000.0)
    } else {
        v.to_string()
    }
}

/// The run header every mock draws, so the comparison is of the layout and not of its chrome.
///
/// The right-hand side carries the fixture's [`Provenance`] badge as well as its elapsed time. That
/// is deliberate and it is A-145's rule: the recorded cases are replayed to a chosen cursor, which
/// is the one structural thing the projection invents, so it is stated **on screen** in every
/// drawing rather than in a doc comment somewhere the reader will not be.
pub(crate) fn header(fx: &Fixture, vp: Viewport, theme: &Theme, sub: &str) -> Line<'static> {
    let right = format!("{} · {} elapsed", fx.provenance.badge(), ms(fx.elapsed_ms));
    let left = format!("◆ {}  {sub}", fx.title);
    let gap = vp.cols.saturating_sub(width(&left) + width(&right)).max(1);
    clip(
        Line::from(vec![
            Span::styled("◆ ", theme.accent_style()),
            Span::styled(
                fx.title.clone(),
                Style::default().add_modifier(Modifier::BOLD),
            ),
            Span::styled(format!("  {sub}"), theme.muted_style()),
            Span::raw(" ".repeat(gap)),
            Span::styled(right, theme.muted_style()),
        ]),
        vp.cols,
    )
}

/// Colour for a step's status glyph, shared so the five read as one product.
pub(crate) fn status_style(status: Status, theme: &Theme) -> Style {
    match status {
        Status::Done => theme.ok_style(),
        Status::Running => theme.accent_style(),
        Status::Failed => theme.err_style(),
        Status::Pending => theme.muted_style(),
    }
}

/// The recommendation this story exists to produce. Five pictures and no decision is the failure
/// mode, so the decision ships in the artifact rather than only in a review comment.
pub const RECOMMENDATION: &str = "\
BUILD THE AXES, AND SHIP THESE DEFAULTS: depth ALL · condense ON · pane OFF.
Do not adopt a picture. And do not expect the axes to give you mock 3 — they do not, and section 2
is the measurement that says so.

═══ A-146: THE COMPOSITION WAS TESTED AND IT DOES NOT HOLD ═══

A-146 built the three controls the owner named — a depth limit, condense-completed, an optional
detail pane — and swept all twelve combinations across four load cases and the same 18x28 viewport
envelope the five mocks are held to. The claim under test was: 'the flat thread with condensing and
a depth limit and an optional pane IS the split'.

1. WHAT THE COMPOSITION DOES REPRODUCE, EXACTLY. A partial result is still a result.
   - THE NESTED TREE is `depth 6 · condense off · pane off` — 6 being plan.rs's MAX_TREE_DEPTH,
     which mock 2 borrows from the live plan renderer. The same steps, on every load case, at
     every viewport tested. Mock 2 is a point in this space.
   - THE FLAT THREAD'S VIEW is `depth ∞ · condense off · pane off`, on every case.
   - Mocks 4 and 5 are not in the space and were never claimed to be. A-145 already dropped mock 5
     from candidacy; mock 4's axis is time, which no show/hide control produces.

2. ⚠ THE SPLIT IS NOT A POINT IN THIS SPACE, AND THE BOUNDARY IS EXACT.
   THE AXES REACH THE SPLIT ONLY WHEN THE RUN HAS ONE TOP-LEVEL STEP, OR THE TERMINAL IS TOO SHORT
   FOR THE SPLIT TO DRAW ITS OWN RULE. Give it nine turns and the rows to show them, and nothing in
   the space reaches it. Measured over the full envelope: on the real nine-turn session there are 24
   viewports where the split both draws its whole rail and withholds something, and ZERO matches in
   them; on the fan-out case, 42 viewports and zero matches. On ONE recorded turn, 60 of 60 match.

   THE STRUCTURAL REASON. Mock 3's rail is not 'condense completed'. It is one row per top-level
   step PLUS THE FOCUSED TOP-LEVEL STEP'S ENTIRE SUBTREE — including that subtree's COMPLETED work,
   which condensing by definition folds away. So the rail discriminates on FOCUS and condensing
   discriminates on STATUS. With one root the two rules coincide; with nine turns they cannot.

   ⚠ WHAT A-137 ACTUALLY OWES, THEN: not a fourth picture but a fourth DECISION — condensing's
   GRANULARITY. 'Finished work collapses to one row' does not say at what level, and the answer
   changes what you get. Fold uniformly (what this module implements) and you get every turn's shape
   at one row per phase. Fold only at the top level and you get mock 3's rail. Both are defensible;
   they are not the same view, and a one-bit `condense` flag cannot express the difference. Decide
   it explicitly rather than inheriting whichever one gets written first.

   ⚠ AN EARLIER READING OF THIS SAME MEASUREMENT, taken only at 100x28, said the axes agree with the
   split 'exactly when the split is hiding nothing'. The full sweep falsifies it: at 64x10 the split
   withholds 10 of the tidy case's 18 steps and two configurations still match. The agreement is
   about ONE ROOT AND TOO FEW ROWS. The distinction matters — the first phrasing would have sent
   A-137 hunting for the divergence in the elision policy instead of in the rail's rule.

3. ⚠ THE DEPTH LIMIT DOES NOT TURN THE THREAD INTO THE TREE. MOCKS 1 AND 2 ARE THE SAME POINT.
   The owner's table assigned the depth axis the job of moving between the flat thread and the tree.
   It cannot, because depth is not what separates them. The thread draws every step at every depth
   and spends no column on indentation; the tree draws every step at every depth and spends three
   columns per level. NEITHER HIDES ANYTHING THE OTHER SHOWS — on both recorded cases their step
   sets are identical, and the composed view at `depth ∞ · condense off · pane off` matches both.

   So the thread↔tree axis is INDENTATION: a drawing decision, invisible to any show/hide control,
   and a FOURTH axis if A-137 wants both pictures. The depth limit is a real and useful control —
   it is simply not this one. (It is what makes the deep-nesting case readable, and A-145 measured
   real nesting at three levels, so on a real run it never has to fire at all.)

4. ⚠ THE INVERSION: ON A REAL RUN, CONDENSING IS WHAT BUYS THE ROOM TO SHOW A FAILURE.
   The story's stated risk was that condensing would swallow a failed step and flatter the run. The
   opposite is what happens. Session s_1477 turn 7 ran `git_stage` against a path that no longer
   existed; it failed with exit 128, and the `execute_batch` phase around it then closed OK — a DONE
   parent holding a FAILED child, a shape nobody would have authored and which only exists here
   because the fixture is a real capture. On the nine-turn case at 100x28:
     - condense OFF: the failure is 166 steps back and the terminal has long since scrolled past it.
     - condense ON:  six clean turns fold to a row each, TURN 7 REFUSES TO FOLD BECAUSE IT HOLDS A
                     FAILURE, and the failed git_stage is on screen with its siblings folded to +2.
   The rule that makes this work is that a subtree is condensable only if it is entirely finished
   AND entirely successful. The two halves are stated separately in `axes::condensable` so that a
   later change to what 'finished' means cannot take the failure rule with it.

5. THE FLOORS, RE-MEASURED PER CONFIGURATION — AND THIS RETIRES A CLAIM FROM THE LAST ROUND.
   A-144 charged the split a 64x10 floor and called it the layout's main cost, recommending mock 1
   as a separate sub-64-column fallback. The floor is the PANE'S, not the layout's: with the pane
   off the composed view draws every load case at 40x6 — the flat thread's floor, the lowest of the
   five — and with it on it refuses one column under 64 exactly as mock 3 does.
   ⚠ SO THE SUB-64-COLUMN FALLBACK IS NOT A SECOND LAYOUT. IT IS THIS LAYOUT WITH A TOGGLE OFF.
   That is the concrete thing making the pane optional buys, and it is why `pane` defaults to off.

6. THE DEFAULTS, AND WHAT EACH ONE SHOWS AND HIDES. Every axis defaults to the setting that
   withholds least, and 'least' means something different on each — which is why this is three
   arguments and not one ratio.

   DEPTH = ALL.
     shows  every level of nesting.
     hides  nothing. Zero depth elisions anywhere in the envelope, on any case.
     why    A-145 measured real nesting at THREE levels (turn > loop phase > op). The eight-level
            case that cost the tree A-144's comparison is a shape this log has never recorded, so a
            limit set against it would pay a real cost to solve an imagined problem. Keep the
            control for the fan-out a sub-agent produces; do not arm it by default. A default depth
            that hid a sub-agent's work would be the flattering-view failure this epic exists to
            avoid, and where it does fire it names the number of LEVELS withheld and how many of the
            withheld steps failed — 'there is more below' is not an answer a reader can act on.

   CONDENSE = ON.
     shows  every top-level step; full structure wherever a failure lives; the running path always.
     hides  finished, wholly successful subtrees — each folded into a row that carries `+N`, plus
            one summary line saying how many steps went into how many rows.
     why    it is the single biggest effect available (191 steps to a ~29-row rail) and, per point
            4, it is what surfaces the failure rather than what buries it. ⚠ Temper the expectation
            with A-145's second correction: the win is CONCENTRATED, not uniform. 36 of 55 real
            phases are exactly one step, where folding saves nothing; one is 57, where the whole
            win lives. Do it — one phase of 57 is reason enough — but do not expect the row count
            to stop tracking the run.

   PANE = OFF.
     shows  the rail at full terminal width, which is where a row can still carry an OP'S ARGUMENT.
            A-145 measured mock 3's 40-column rail down to op-and-timing with the argument gone.
     hides  the focused step's token cost and output tail — one keystroke away, not a relayout.
     why    per point 5 it is the axis that owns the 64x10 floor, and at 52 columns — the width A-145
            notes most of this is actually read at — pane-on refuses entirely while pane-off draws.
            A default that refuses to draw in the operator's usual terminal is not a default.

⚠ WHAT REMAINS TRUE FROM A-144 AND A-145. Condensing first is still right and is still most of the
win; the split's second column still buys the only place to put token cost and a streaming tail
beside the chain that produced it, which is why the pane is an axis rather than a deletion; and the
condensed tree is still the honest runner-up A-145 promoted it to — it is now literally the default
this section recommends. What changed is that 'build mock 3' has become 'build the controls, and
here are the settings', and that mock 3's rail turns out to encode a rule the three controls cannot
say. Everything below this line is the A-144/A-145 reasoning, left intact.

═══ A-144/A-145's ORIGINAL RECOMMENDATION, SUPERSEDED ABOVE BUT NOT EDITED ═══

FIRST, CONDENSE FINISHED PHASES. THEN BUILD MOCK 3 — the split (condensed rail + detail pane) —
with mock 1 as its sub-64-column fallback. The two are separable, and the first is most of the win.

═══ A-145: RE-CHECKED AGAINST A REAL RECORDED RUN — CONFIRMED, WITH THREE CORRECTIONS ═══

The two load-bearing cases are no longer hand-authored. They are a projection of session `s_1477`
out of `~/.flux/events.db` — nine turns, 33 minutes, 191 steps, gpt-5.5 auditing this repo's docs,
fixing the gaps, committing them and cutting a release. See `loopmock::capture`.

The headline survives: condense first, then build the split, thread as the fallback. What the real
run changes is *how much* the condensing buys and *why* the split is worth the second column.

1. CONDENSING IS SUB-LINEAR, NOT CONSTANT — and the win is concentrated in one phase, not spread.
   191 steps condense to a 25-row rail: a 7.6x saving, and the single biggest effect available.
   But the fixture's version of this claim was stronger than the truth. Two reasons.
   (a) The depth-0 unit of a real *session* is a TURN, and turns accumulate: nine turns are nine
       rail rows before a step is drawn, and the focused turn then expands in full. So the rail
       grows with the conversation even though it does not grow with the steps — 25 rows fits a
       28-row terminal and does not fit the 20-row one this is most often read in.
   (b) Real phases are LUMPY. The 55 phases in this session are: 36 of exactly one step, then
       2, 2, 3, 3, 5, 5, 5, 7, 8, 17, 19 — and one of 57. Condensing a one-step phase saves
       nothing; two thirds of the real phases are one-step. The entire win lives in the handful of
       fat ones. The hand-authored fixture had evenly-sized phases of 3-6 because somebody wrote
       evenly-sized phases, and that made condensing look uniformly profitable. It is not; it is
       profitable in bursts. A-137 should still do it — one phase of 57 is reason enough — but it
       should not expect the row count to become independent of the run.

2. ⚠ THE SPLIT AND THE THREAD HIDE THE SAME NUMBER OF STEPS. This is the correction that most
   changes the reasoning. On the long-run case at 100x28 both mock 1 and mock 3 report `166 of 191
   steps not shown`. The split's advantage is NOT that it shows more; it is that it shows a
   DIFFERENT 25 — every one of the nine turns plus the current turn in full, where the thread shows
   the last 25 rows and nothing at all about turns 1-7. Coverage, not capacity. That is still a
   real advantage and still the right call, but the old phrasing ('the only one that still shows
   the whole run') was an artifact of a fixture whose whole run was one run rather than nine turns.

3. THE TREE MOVES UP AND MOCK 5 DROPS OUT ENTIRELY.
   - Real nesting is THREE levels (turn > loop phase > op), not the eight the hand-authored
     deep-nesting case invented. The indentation tax that cost mock 2 the comparison is charged
     against a shape this log has never recorded. At 100 columns on the real run the tree is the
     most legible of the five and — unlike the split's rail, which is down to op-and-timing — it
     still shows each op's ARGUMENT. If A-137 wanted one column instead of two, the condensed tree
     is now the honest runner-up rather than a distant one.
   - Mock 5 is worse than A-144 said, for a reason A-144 could not have seen. Its premise is that
     the model is called from an authored program you can read like source. This loop does not
     work that way: the captured session accepted 127 plans and EVERY ONE OF THEM IS A SINGLE OP.
     There is no DAG. The mock draws one program line and hides 189 of 191 steps. And no run in the
     store persists `plan_ast` at all, so even the syntax highlighting in A-144's mock-5 snapshots
     was a picture of a payload the durable log does not contain. Keep it for A-138's per-step
     expansion; it is not a candidate for a live view.
   - Mock 4 gains a specific defect it did not have against invented timings: real durations span
     1 ms to 344 s. On a linear axis that renders roughly nine steps in ten as a sub-cell tick, so
     the layout whose primary axis is time cannot show most of the time it is drawing.

4. WHAT THE REAL RUN CONFIRMS, NAMED SO THE CLAIM IS ANCHORED. The property that did the
   confirming is the ONE-STEP PHASE COMBINED WITH THE FAT ONE: a layout whose cost is per-step
   pays for turn 5's 57-step `explore` in full, and a layout whose cost is per-phase pays one row
   for it and one row for each of the 36 phases that were a single step anyway. That asymmetry is
   real, it is measured, and nobody designed it.

⚠ Everything below this line is A-144's reasoning against the hand-authored fixture. It is left
intact and unedited so the two can be compared; where the sections above disagree with it, the
sections above are the measurement.

⚠ READ THIS BEFORE THE REST — the comparison is confounded, and in mock 3's favour.
Only mock 3 was given progressive disclosure. Its rail pre-filters to top-level steps plus the
focused subtree (`split.rs`, `rail_rows`) before the shared scroll policy ever runs; mocks 1 and 2
draw one row per step at every depth by construction, so of course they scroll off. The shared
`window` helper keeps scrolling honest between the five, but it does nothing about the filter
applied ahead of it. So when the long-run case shows mock 3 holding the whole run while the thread
and the tree sit at `↑ 23`, that gap measures **condensing**, not **two columns**. A condensed
one-column thread would hold the whole run too — nine top-level rows plus the running phase's four
children, thirteen rows, against 49 steps; `condensing_and_not_the_second_column_is_what_makes_
the_long_run_fit` measures exactly that. Take the cheap lesson first, and read what follows as the
case for the *second* column only.

What the second column buys, after discounting the confound. Three things survive it, all from the
deep-nesting and tidy cases rather than the long-run one:
  - It is the only layout that shows a model call's token cost and its streaming output tail
    beside the chain that produced it. A one-column thread has nowhere to put three lines of live
    output without becoming a different layout.
  - A-142's inspection pane does not need building; the right column already is it. The other four
    answer \"where does the pane go\" with a sheet or a bottom split, so A-142 would relayout
    whatever A-137 shipped.
  - A-140's pause has an unambiguous home — the focused rail row, beside the step it would pause.

What it gives up — the honest list.
  1. Width, badly. 64 columns and 10 rows, both the highest floors of the five; the snapshots show
     it refusing in *every* case at 52 columns while all four others still draw. This is the one
     place the split is the worst option and it is not a small place. Hence the fallback: below its
     floor A-137 should render mock 1 rather than refuse. The mocks refuse instead, deliberately,
     so the cost shows up in the picture rather than in a footnote.
  2. Content in the rail. At 40 rail columns a leaf row is `→ read  7.4s` — the op and its timing,
     with the argument gone. Compare the fan-out case: the tree shows six workers and what each is
     doing *including the argument*; the split shows six workers and their current ops, and the
     arguments for one.
  3. One narrative. A rail beside a pane is not something you scroll back through. This answers the
     design doc's open question (\"scrollback-inline or a pane\") in favour of the pane, and the
     transcript keeps the scrollback.
  4. Focus state. It is the only layout needing a selection, so it is the only one needing input
     handling and a focus policy — follow the running step, or hold where the operator put it —
     before it renders correctly at all. Budget that into A-137; the other four do not spend it.

Runner-up: mock 2, the tree. At 100 columns it is the most legible drawing of what a run is
*shaped* like and the only one where a fan-out looks like a fan-out with every worker's argument
visible. It loses on the width tax: indentation compounds, and by the deep-nesting case at 52
columns the connectors have taken half the terminal. Take its connectors with you — the split's
pane already draws its children with them, and that is not a coincidence. ⚠ And note it would look
considerably better than it does here if it were condensed too; the confound above cuts against it
harder than against any other mock.

Do not build as the top-level view: mock 1 alone (the scope column gets squeezed exactly when there
is enough structure for it to matter, and concurrency reads as interleaving), or mock 5. Mock 5 is
the right answer for A-138's expansion and the wrong one for a live view — its snapshots show why
twice over: the program does not move, so most rows are always the parts that are not running, and
mapping runtime steps back onto program nodes misattributes as soon as a sub-agent runs a program
of its own (see the fan-out case, where six workers' `glob` calls land on the parent's `glob`
node). A-138 should expand *one step* into its graph, which is exactly what the split's pane has
room to do.";

/// [`FIDELITY`] as markdown — **the second deliverable of A-145**, and the start of the table
/// [C-422](../../../../docs/stories/C-422-the-render-projection.md) owes. Reconstructing a real
/// session is where the durable log's limits actually show up; leaving them in a doc comment is how
/// they get rediscovered.
fn fidelity_table() -> String {
    let mut out = String::from(
        "## What a recorded case is worth, field by field\n\n\
         The reconstruction (`loopmock::capture`) rebuilt everything below from the durable log.\n\
         *faithful* = taken from a durable event with no invention · *approximated* = synthesised,\n\
         and the note says exactly what · *absent* = not recoverable, so the render shows nothing\n\
         rather than a guess. ⚠ Several rows are absent **despite being recorded** — the log holds\n\
         the value but nothing anchors it to a moment.\n\n",
    );
    out.push_str("| what the view wants | durable source | fidelity | note |\n");
    out.push_str("|---|---|---|---|\n");
    for row in FIDELITY {
        out.push_str(&format!(
            "| {} | {} | **{}** | {} |\n",
            row.concept,
            row.source,
            row.fidelity.label(),
            row.note.replace('|', "\\|"),
        ));
    }
    out.push('\n');
    out
}

/// **A-146's section of the snapshot set** — the three axes, drawn rather than described.
///
/// The pictures are chosen to carry the findings that a reader would otherwise have to take on
/// trust, above all the recorded failure: the same nine-turn run drawn with condensing off and on,
/// so that "condensing is what buys the room to show the failure" is something you can see instead
/// of a claim in a paragraph.
fn axes_section() -> String {
    let theme = Theme::MONO;
    let mut out = String::new();
    out.push_str("# A-146 — the same five, as three knobs\n\n");
    out.push_str(
        "A-144 drew five layouts and A-145 re-checked them against a real recorded run. A-146 asks \
         a different question: are the five **points in a space with three orthogonal axes** — a \
         depth limit, condense-completed, and an optional detail pane — so that A-137 can build \
         *controls* and choose *defaults* rather than adopt a picture?\n\n\
         **The answer is no, and the refutation is the deliverable.** Two of the five are \
         reproduced exactly; the split is not reachable at all; and two of the five turn out to be \
         the *same point*. The measurement is in the recommendation above, section by section. What \
         follows is the evidence.\n\n",
    );

    out.push_str("## What each configuration reproduces\n\n");
    out.push_str("| configuration | floor | reproduces |\n|---|---|---|\n");
    for axes in AXIS_SPACE {
        let (c, r) = axes.floor();
        let what = match (axes.depth, axes.condense, axes.pane) {
            (axes::Depth::All, false, false) => {
                "**the flat thread's view** (and the tree's, on a real run) — exactly"
            }
            (axes::Depth::All, false, true) => "the split *only* where the split hides nothing",
            (axes::Depth::All, true, false) => "**the recommended default**",
            _ => "—",
        };
        out.push_str(&format!("| `{}` | {c}×{r} | {what} |\n", axes.label()));
    }
    out.push_str(
        "\nAnd separately, `depth 6 · condense off · pane off` reproduces **the nested tree** \
         exactly, on every load case — 6 being `plan.rs`'s `MAX_TREE_DEPTH`, the bound mock 2 \
         borrows from the live plan renderer.\n\n",
    );

    // ⚠ The centrepiece. A `Done` phase holding a `Failed` op is a shape nobody would author, and
    // it only exists here because the fixture is a real capture — so it is drawn, twice, rather
    // than asserted once.
    out.push_str("## ⚠ The recorded failure, with condensing off and on\n\n");
    out.push_str(
        "Session `s_1477` turn 7 ran `git_stage` against a path that no longer existed. It failed \
         with `exit 128` — and the `execute_batch` phase around it then closed **ok**. That is a \
         `Done` parent holding a `Failed` child, which is exactly the shape that makes \"finished \
         work collapses to one row\" dangerous, and it is not a shape anybody would have thought \
         to author.\n\n\
         The story's stated risk was that condensing would swallow it. On the real nine-turn run \
         the opposite happens — **condensing is what buys the room to show it.** Both drawings \
         below are the same run at the same viewport.\n\n",
    );
    for (axes, caption) in [
        (
            Axes {
                depth: Depth::All,
                condense: false,
                pane: false,
            },
            "**condense off** — the failure is 166 steps back, and the window has scrolled past it. \
             There is no `✗` on this screen.",
        ),
        (
            Axes::DEFAULT,
            "**condense on (the default)** — six clean turns fold to a row each, **turn 7 refuses \
             to fold because it holds a failure**, and `✗ → git_stage` is on screen with its clean \
             sibling folded to `+2`.",
        ),
    ] {
        out.push_str(&format!(
            "### long run · `{}` · {}×{}\n\n{caption}\n\n```text\n{}```\n\n",
            axes.label(),
            WIDE.cols,
            WIDE.rows,
            render_axes(axes, LoadCase::LongRun, WIDE, &theme).to_plain(),
        ));
    }

    out.push_str("## ⚠ Mocks 1 and 2 are the same point\n\n");
    out.push_str(
        "The depth limit was supposed to move between the flat thread and the tree. It cannot: \
         neither hides anything the other shows. Below, the composed view at `depth ∞ · condense \
         off · pane off` beside both mocks on the same recorded turn — three different pictures, \
         one view.\n\n",
    );
    for (name, plain) in [
        (
            "composed · depth ∞ · condense off · pane off".to_string(),
            render_axes(
                Axes {
                    depth: Depth::All,
                    condense: false,
                    pane: false,
                },
                LoadCase::Tidy,
                WIDE,
                &theme,
            )
            .to_plain(),
        ),
        (
            Mock::Thread.spec().name.to_string(),
            render(Mock::Thread, LoadCase::Tidy, WIDE, &theme).to_plain(),
        ),
        (
            Mock::Tree.spec().name.to_string(),
            render(Mock::Tree, LoadCase::Tidy, WIDE, &theme).to_plain(),
        ),
    ] {
        out.push_str(&format!("### {name} · tidy\n\n```text\n{plain}```\n\n"));
    }

    out.push_str("## Each axis on its own\n\n");
    out.push_str(
        "The three are independent: each is settable without the others and each changes the \
         drawing with the other two held fixed.\n\n",
    );
    for (axes, case, caption) in [
        (
            Axes {
                depth: Depth::Levels(2),
                condense: false,
                pane: false,
            },
            LoadCase::FanOut,
            "**the depth axis alone.** Where it bites it says how many *levels* went with it, not \
             merely that something did — a sub-agent's whole run can live in one withheld level.",
        ),
        (
            Axes {
                depth: Depth::All,
                condense: true,
                pane: true,
            },
            LoadCase::LongRun,
            "**all three on.** The nearest point in the space to mock 3 — and, per section 2 of the \
             recommendation, still not mock 3.",
        ),
    ] {
        out.push_str(&format!(
            "### {} · {} · {}×{}\n\n{caption}\n\n```text\n{}```\n\n",
            case.name(),
            axes.label(),
            WIDE.cols,
            WIDE.rows,
            render_axes(axes, case, WIDE, &theme).to_plain(),
        ));
    }

    out.push_str("## The floor travels with the pane\n\n");
    out.push_str(
        "A-144 charged the split a 64×10 floor and recommended the flat thread as a separate \
         sub-64-column fallback. The floor belongs to the **pane**: with it off, the same view \
         draws at 40×6 — the lowest floor of the five. So the fallback is not a second layout, it \
         is this layout with a toggle off.\n\n",
    );
    for (axes, vp) in [
        (Axes::DEFAULT, Viewport { cols: 40, rows: 6 }),
        (Axes::DEFAULT, NARROW),
        (
            Axes {
                pane: true,
                ..Axes::DEFAULT
            },
            NARROW,
        ),
        (
            Axes {
                pane: true,
                ..Axes::DEFAULT
            },
            Viewport { cols: 64, rows: 10 },
        ),
    ] {
        out.push_str(&format!(
            "### `{}` · tidy · {}×{}\n\n```text\n{}```\n\n",
            axes.label(),
            vp.cols,
            vp.rows,
            render_axes(axes, LoadCase::Tidy, vp, &theme).to_plain(),
        ));
    }
    out
}

/// The committed side-by-side comparison, as markdown. This is the artifact a reviewer reads
/// instead of running anything; `the_snapshot_set_matches_the_renderers` keeps it honest.
pub fn snapshot_document() -> String {
    let theme = Theme::MONO;
    let mut out = String::new();
    out.push_str(
        "<!-- GENERATED by `cargo test -p flux-tui --test loop_mocks` (A-144). Do not hand-edit;\n\
         regenerate with FLUX_UPDATE_GOLDEN=1, which rewrites this file and then fails on purpose. -->\n\n",
    );
    out.push_str("# A-144 / A-145 — five loop-view mocks, side by side\n\n");
    out.push_str(
        "Five hard-coded layouts drawing one run. Nothing here is wired to a live agent; see\n\
         `crates/flux-tui/src/loopmock/mod.rs`.\n\n\
         ⚠ **Two of the four load cases are a REAL RECORDED RUN, and two are not** (A-145). The\n\
         tidy and long-run cases are a projection of session `s_1477` out of `~/.flux/events.db` —\n\
         nine turns, 33 minutes, 191 steps of this repo's own docs being audited, fixed, committed\n\
         and released. Deep nesting and fan-out are still hand-authored, because **the durable log\n\
         cannot currently produce them**: no session that records op output (post-C-43) also spawns\n\
         sub-agents. Every render says which it is in its header, so the two can never be confused\n\
         for one another; the fidelity table below says what a recorded case is worth field by\n\
         field.\n\n\
         Each mock is drawn under all four cases, plus a narrow terminal, its own floor, and one\n\
         step under that floor in each dimension.\n\n\
         ⚠ **The comparison is confounded and the recommendation says so** — only mock 3 was given\n\
         progressive disclosure, so the long-run gap measures condensing rather than a second\n\
         column. Read the warning at the top of the recommendation before the pictures.\n\n\
         ⚠ **The capture is a snapshot and cannot be refreshed.** Re-running the capture command\n\
         records a *different* run; nothing regenerates that file.\n\n",
    );

    out.push_str("## The recommendation\n\n```text\n");
    out.push_str(RECOMMENDATION);
    out.push_str("\n```\n\n");
    out.push_str(&fidelity_table());
    out.push_str("## At a glance\n\n");
    out.push_str("| mock | primary axis | optimizes for | gives up | floor |\n");
    out.push_str("|---|---|---|---|---|\n");
    for mock in MOCKS {
        let s = mock.spec();
        out.push_str(&format!(
            "| {} | {:?} | {} | {} | {}×{} |\n",
            s.name, s.axis, s.optimizes_for, s.gives_up, s.min_cols, s.min_rows
        ));
    }
    out.push('\n');

    for mock in MOCKS {
        let s = mock.spec();
        out.push_str(&format!("## {}\n\n", s.name));
        out.push_str(&format!("- **Primary axis:** {:?}\n", s.axis));
        out.push_str(&format!("- **Optimizes for:** {}\n", s.optimizes_for));
        out.push_str(&format!("- **Gives up:** {}\n", s.gives_up));
        out.push_str(&format!(
            "- **A-140 pause control:** {}\n",
            s.pause_affordance
        ));
        out.push_str(&format!(
            "- **A-142 inspection pane:** {}\n",
            s.inspection_pane
        ));
        out.push_str(&format!(
            "- **Floor:** {} cols × {} rows (below either, it says so instead of mangling itself)\n\n",
            s.min_cols, s.min_rows
        ));

        for case in LOAD_CASES {
            for vp in [WIDE, NARROW] {
                let r = render(mock, case, vp, &theme);
                out.push_str(&format!(
                    "### {} · {} · {}×{}\n\n",
                    s.name,
                    case.name(),
                    vp.cols,
                    vp.rows
                ));
                if !r.elisions.is_empty() {
                    let notes: Vec<String> = r
                        .elisions
                        .iter()
                        .map(|e| format!("{} {}", e.hidden, e.what))
                        .collect();
                    out.push_str(&format!("_withheld: {}_\n\n", notes.join(", ")));
                }
                out.push_str("```text\n");
                out.push_str(&r.to_plain());
                out.push_str("```\n\n");
            }
        }

        // At its floor exactly, then one under it in each dimension. The floor render is the more
        // interesting of the three: it is the smallest terminal in which this layout is still
        // itself, and for one mock that is a much bigger box than for the rest.
        let at = Viewport {
            cols: s.min_cols,
            rows: s.min_rows,
        };
        let r = render(mock, LoadCase::FanOut, at, &theme);
        out.push_str(&format!(
            "### {} · at its floor · fan-out · {}×{}\n\n```text\n{}```\n\n",
            s.name,
            at.cols,
            at.rows,
            r.to_plain()
        ));
        for (under, dim) in [
            (
                Viewport {
                    cols: s.min_cols - 1,
                    rows: s.min_rows,
                },
                "one column under",
            ),
            (
                Viewport {
                    cols: s.min_cols,
                    rows: s.min_rows - 1,
                },
                "one row under",
            ),
        ] {
            let r = render(mock, LoadCase::Tidy, under, &theme);
            out.push_str(&format!(
                "### {} · {dim} its floor · {}×{}\n\n```text\n{}```\n\n",
                s.name,
                under.cols,
                under.rows,
                r.to_plain()
            ));
        }
    }
    out.push_str(&axes_section());
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn clip_never_exceeds_its_budget_and_marks_the_cut() {
        let line = Line::from(vec![Span::raw("abcdef"), Span::raw("ghijkl")]);
        let out = clip(line, 8);
        let text: String = out.spans.iter().map(|s| s.content.to_string()).collect();
        assert_eq!(text, "abcdefg…");
        assert_eq!(width(&text), 8);
    }

    #[test]
    fn clip_leaves_a_fitting_line_alone() {
        let line = Line::from(Span::raw("short"));
        assert_eq!(clip(line, 40).spans[0].content, "short");
    }

    #[test]
    fn pad_squares_a_column_off() {
        let out = pad(Line::from(Span::raw("ab")), 6);
        let text: String = out.spans.iter().map(|s| s.content.to_string()).collect();
        assert_eq!(width(&text), 6);
    }

    #[test]
    fn the_tally_derives_the_hidden_count_rather_than_trusting_a_renderer() {
        let mut tally = Tally::new(20);
        tally.drew(0..7);
        let render = tally.finish(Vec::new(), WIDE, &Theme::MONO);
        assert_eq!(render.elisions.len(), 1);
        assert_eq!(render.elisions[0].hidden, 13);
        assert!(render.to_plain().contains(&render.elisions[0].marker));
    }

    #[test]
    fn a_marker_that_did_not_survive_composition_is_forced_onto_the_screen() {
        // The safety net exercised directly: a renderer that records an elision and then draws
        // nothing mentioning it must not be able to produce a silent truncation. Every renderer is
        // written so this cannot happen; `finish` is what makes the property unconditional rather
        // than true-for-the-viewports-we-happened-to-test.
        let mut tally = Tally::new(3);
        tally.drew(0..3);
        tally.hid(DETAIL, 4, "+4 more".to_string());
        let lines = vec![
            Line::from(Span::raw("chrome")),
            Line::from(Span::raw("body")),
        ];
        let render = tally.finish(lines, Viewport { cols: 20, rows: 2 }, &Theme::MONO);
        assert!(
            render.to_plain().contains("+4 more"),
            "the elision was recorded but never drawn:\n{}",
            render.to_plain()
        );
        assert!(render.lines.len() <= 2);
    }

    #[test]
    fn the_step_footer_outlives_a_displaced_detail_marker() {
        let mut tally = Tally::new(9);
        tally.drew(0..2);
        tally.hid(DETAIL, 3, "+3 more".to_string());
        let lines = vec![Line::from(Span::raw("x")), Line::from(Span::raw("y"))];
        let render = tally.finish(lines, Viewport { cols: 40, rows: 3 }, &Theme::MONO);
        let plain = render.to_plain();
        for elision in &render.elisions {
            assert!(plain.contains(&elision.marker), "{plain}");
        }
        assert_eq!(render.elisions.len(), 2);
    }

    #[test]
    fn a_complete_drawing_admits_nothing() {
        let mut tally = Tally::new(4);
        tally.drew(0..4);
        assert!(tally
            .finish(Vec::new(), WIDE, &Theme::MONO)
            .elisions
            .is_empty());
    }
}
