// @ts-check

const sidebars = {
  docs: [
    'intro',
    'getting-started',
    {
      type: 'category',
      label: 'Tutorial',
      collapsed: false,
      items: [
        'tutorial',
        'tutorial/first-agent',
        'tutorial/first-flow',
        'tutorial/first-app',
      ],
    },
    'whats-new',
    'concepts',
    'infrastructure',
    'troubleshooting',
    {
      type: 'category',
      label: 'Agent',
      items: [
        'agent/cli',
        'agent/tui',
        'agent/agent-loop',
        'agent/providers',
        'agent/claude-code',
        'agent/safety',
        'agent/http-api',
        'agent/a2a',
        'agent/a2a-conformance',
        'agent/programs',
        'agent/datasources',
        'agent/fleet',
        'agent/endpoints',
        'agent/saved-flows',
        'agent/project-context',
        'agent/skills-and-roles',
        'agent/claude-compat',
        'agent/time-machine',
        'agent/cost',
        'agent/realtime',
      ],
    },
    {
      type: 'category',
      label: 'Channels',
      items: [
        'channels/overview',
        'channels/inventory',
        'agent/slack-channel',
      ],
    },
    {
      type: 'category',
      label: 'Improvement',
      items: ['agent/improvement'],
    },
    {
      type: 'category',
      label: 'Flux-Lang',
      collapsed: false,
      items: [
        'language/overview',
        'language/tour',
        {
          type: 'category',
          label: 'Guide',
          items: [
            'language/flows-and-syntax',
            'language/control-flow',
            'language/pure-data',
            'language/context-packs',
            'language/concurrency',
            'language/reliability',
            'language/durability',
            'language/execution-model',
            'language/modules-and-programs',
          ],
        },
        {
          type: 'category',
          label: 'Reference',
          items: [
            'language/node-reference',
            'language/types-and-effects',
            'language/ops',
            'language/tooling',
            'language/editors',
          ],
        },
        'language/examples',
      ],
    },
    {
      type: 'category',
      label: 'SDK',
      items: [
        'sdk/overview',
        'sdk/sessions',
        'sdk/streaming',
        'sdk/flow-client',
        'sdk/datasources',
        'sdk/agent-lab',
      ],
    },
    {
      type: 'category',
      label: 'Plugins',
      items: [
        'plugins/using-plugins',
        'plugins/gitlab',
        'plugins/slack',
        'plugins/kubernetes',
        'plugins/sql',
        'plugins/authoring',
      ],
    },
    {
      type: 'category',
      label: 'Direction',
      items: ['direction/portable-wasm-runtime'],
    },
    {
      type: 'category',
      label: 'Security',
      items: [
        'security/overview',
        'security/plain-terms',
        'security/credentials',
        'security/plugin-sandbox',
        'security/os-sandbox',
        'security/plugin-trust',
        'security/server-auth',
        { type: 'ref', id: 'agent/safety' },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: ['reference/config', 'reference/storage'],
    },
  ],
};

module.exports = sidebars;
